### ISSUE TITLE
Disable/Enable extensions instead of Removing/Adding extensions when switching Profile

### ISSUE THREAD

**Issue by libinvarghese** [aaronpowell/vscode-profile-switcher#25]
Even though removing and adding extensions works when I switch profiles, sometimes there are those few extensions which I would like to use temporarily (ie enable and disable after usage). In this case
1. either need to switch profile OR
1. have the extension in the `profileSwitcher.extensionsIgnore` in disabled state, and toggle when needed.

Also would it not be easier/faster to disable/enable instead of remove/add?

**Comment by codeunifier** [comment]
@libinvarghese my thoughts exactly! It does keep the extensions tab clean, but it definitely seems like disabling / enabling would be a faster method. At least having the option to uninstall / disable would be really nice!

**Comment by aaronpowell** [comment]
It would be a much better idea to just activate/deactivate extensions but unfortunately, it's not possible. [Here is the docs](https://code.visualstudio.com/api/references/vscode-api#extensions) for a VS Code extension to work with other extensions, and all it provides is access to extensions, but no way to interact with them.

As frustrating as it is, I do agree with the reason for this, as it means that extensions are protected from one another, you can't have an extension that comes in and turns off others, that'd be an avenue for abuse.

This is why the extension will do a backup of extensions before removing them (or at least, attempt to), so that when you "reactivate" it, it doesn't need to be downloaded.
