### ISSUE TITLE
Logic of the vscode-profile-switcher

### ISSUE THREAD

**Issue by butuzov** [aaronpowell/vscode-profile-switcher#5]
Hi Aaron, 

It's a great extension, and I was looking for something like this for months. I have tested it today and found a few things that can improve it. But I think it depends on the workflow of the users.

1. Ability to create "New Profile" (With crystal clear VSC), so you can customize it - save it and use it. 
> So, for example, I want to create a light-themed development for let's say - go programming. But all my current setup is dark and I need to tweak a ton of setting to turn it down. 

2. Ability to have default/base profile which you can in addition to the selected profile.

> This will give me the ability to easy maintain extensions settings + theme settings, but change number of extensions enabled. I just checked settings.json generated by **profile switcher**, I don't want to touch now.  Having more than two profiles will require me to edit tiny settings for all the profiles, not just once. Not sure this is a thing I want

**Comment by aaronpowell** [comment]
Hi @butuzov,

> 1. Ability to create "New Profile" (With crystal clear VSC), so you can customize it - save it and use it.

Do you mean to have a "reset VS Code to factory defaults" sort of option? I'm not sure if that is possible without forcing Code to launch with an entirely new profile path (which I don't think I can do programmatically).

Also, because the changes that you bring in from a profile are merged into the current settings a "factory default" would have to contain each of the settings explicitly as their default to override.

> 2. Ability to have default/base profile which you can in addition to the selected profile.

This does work, as I mentioned above the settings are applied from a profile in an additive fashion, meaning you can do layering of them. This is how I do my presentation settings, I only have the font size increase in that profile and it layers it over the current settings set.

You do have to manually edit your `settings.json` file to achieve this though, because without making the 'Save Profile' feature more complex there's no better way from the VS Code extensibility points to get the user to select what settings they want in the profile.
